<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>Thaylon Lopes</Authors>
    <Company>Thaylon Lopes</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/thaylonlopes/DataHelpers</PackageProjectUrl>
    <RepositoryUrl>https://github.com/thaylonlopes/DataHelpers</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <NoWarn>$(NoWarn);1591;NETSDK1206</NoWarn>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>csharp;dotnet;data-helpers;dapper;mongodb;redis;caching;query-builder;paging</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)assets\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests')) Or $(MSBuildProjectName.Contains('.Showcase')) Or $(MSBuildProjectName.StartsWith('Example.')) Or $(MSBuildProjectName.EndsWith('.Benchmarks'))">
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
