<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AuditLogger\AuditLogger.csproj" />
    <ProjectReference Include="..\..\Caching.Helpers\Caching.Helpers.csproj" />
    <ProjectReference Include="..\..\Dapper.Helpers\Dapper.Helpers.csproj" />
    <ProjectReference Include="..\..\DataImportExport.Helpers\DataImportExport.Helpers.csproj" />
    <ProjectReference Include="..\..\DataMapping.Helpers\DataMapping.Helpers.csproj" />
    <ProjectReference Include="..\..\MongoDriver.Helpers\MongoDriver.Helpers.csproj" />
    <ProjectReference Include="..\..\PagingFiltering.Helpers\PagingFiltering.Helpers.csproj" />
    <ProjectReference Include="..\..\QueryBuilder.Helpers\QueryBuilder.Helpers.csproj" />
  </ItemGroup>

</Project>
