<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>TL.Caching.Helpers</PackageId>
    <Version>0.0.1-beta</Version>
    <Authors>Thaylon Lopes</Authors>
    <Description>Biblioteca utilitária avançada para caching distribuído e em memória com suporte a arquitetura multinível L1/L2, resiliência e locking distribuído.</Description>
    <Title>Caching.Helpers</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;NETSDK1206</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Ignite" Version="2.16.0" />
    <PackageReference Include="EntityFrameworkCore.NCache" Version="5.3.4" />
    <PackageReference Include="EnyimMemcachedCore" Version="3.2.4" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.0" />
    <PackageReference Include="Polly" Version="8.5.0" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
    <PackageReference Include="RedLock.net" Version="2.3.2" />
  </ItemGroup>

</Project>
