<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>TL.Caching.Helpers</PackageId>
    <Title>Caching.Helpers</Title>
    <Description>Biblioteca utilitária avançada para caching distribuído e em memória com suporte a arquitetura multinível L1/L2, resiliência e locking distribuído.</Description>
    <NoWarn>$(NoWarn);1591;NETSDK1206</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Ignite" />
    <PackageReference Include="EntityFrameworkCore.NCache" />
    <PackageReference Include="EnyimMemcachedCore" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Polly" />
    <PackageReference Include="prometheus-net" />
    <PackageReference Include="RedLock.net" />
  </ItemGroup>

</Project>
