<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>TL.QueryBuilder.Helpers</PackageId>
    <Version>0.0.1-beta</Version>
    <Authors>Thaylon Lopes</Authors>
    <Description>Construtor de consultas fluente e poliglota com suporte a SQL Server, PostgreSQL, MySQL, Oracle, MongoDB e DynamoDB.</Description>
    <Title>QueryBuilder.Helpers</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="MongoDB.Bson" Version="3.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
  </ItemGroup>

</Project>
