<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>TL.PagingFiltering.Helpers</PackageId>
    <Title>PagingFiltering.Helpers</Title>
    <Description>Biblioteca para paginação avançada (Offset e Cursor) e composição booleana de filtros via Specification Pattern.</Description>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
